name: Build and Deploy Application

on:
  push:
    branches:
      - main

env: 
    EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
    OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build application
      run: |
        bun install
        bun --bun run build
        
    - name: Stop old application
      if: success()
      run: |
        # Find and kill all running bun processes
        pids=$(pgrep -f bun)
        if [ -n "$pids" ]; then
          sudo kill $pids
        fi
        
    - name: Remove old application and copy new
      if: success()
      run: |
        sudo rm -rf /home/scrapi
        sudo cp -r . /home/scrapi
        cp /.env /home/scrapi
        
    - name: Start new application
      if: success()
      run: |
        cd /home/scrapi
        bun --bun index.ts &
        
    - name: Notify on failure
      if: failure()
      run: echo "Build failed. Old application may not have been stopped or replaced."