name: Build and Deploy Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, scrapi]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        id: build
        run: docker build -t scrapi:latest .
      
      - name: Stop and remove existing container
        if: success()
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^scrapi$'; then
            docker stop scrapi
            docker rm scrapi
          fi
      
      - name: Run new container
        if: success()
        run: |
          docker run -d --name scrapi -p 80:80 scrapi:latest /bin/sh -c "bun run dev --host"
      
      - name: Notify on failure
        if: failure()
        run: echo "Build failed. Old container may not have been stopped or replaced."
