name: Conditional Bun Build and Run with nohup

on:
  push:
    branches:
      - main

jobs:
  local-job:
    runs-on: self-hosted

    steps:
      - name: Navigate to project directory
        run: cd /home/scrapi/scrapi

      - name: Pull latest changes from the repository
        run: git pull

      - name: Remove existing build directory
        run: rm -rf build

      - name: Stop existing bun process
        run: |
          echo "Stopping existing bun process..."
          pkill -f "bun" || echo "No bun process found"

      - name: Run the build process
        id: build
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium'
          CHROME_PATH: '/usr/bin/chromium'

        run: |
          echo "Running bun build..."
          bun --bun run build

      - name: Start the application if build succeeds
        if: ${{ success() }}
        run: |
          echo "Build succeeded, starting the application..."
          nohup bun --bun . > app.log 2>&1 &
