name: Build and Deploy Application
on:
  push:
    branches:
      - main

env:
  
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build project
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium'
          CHROME_PATH: '/usr/bin/chromium'
          run: bun --bun run build
          
      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq -y --no-install-recommends \
            chromium \
            chromium-sandbox \
            fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst

      - name: Stop existing process
        run: |
          if pgrep -f "bun ."; then
            pkill -f "bun ."
          fi

      - name: Run application
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium'
          CHROME_PATH: '/usr/bin/chromium'
        run: |
          nohup bun . > app.log 2>&1 &
          echo $! > .pid

      - name: Notify on failure
        if: failure()
        run: echo "Build or deployment failed."
