name: Bun Build and Reload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:        
      - name: Reload by calling the server
        run: |
          curl -X POST "http://localhost:8081?EBAY_CERT_ID=${{ secrets.EBAY_CERT_ID }}&OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        run: bun install
        
      - name: Run the build process
        id: build
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: bun --bun run build
