name: Bun Build and Reload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted, Linux, X64

    steps:
      - name: Reload by calling the server
        run: curl http://localhost:8081
        
      - name: Run the build process
        id: build
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

        run: bun --bun run build
