name: Build and Deploy Application
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun --bun run build

      - name: Deploy application
        env:
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium'
          CHROME_PATH: '/usr/bin/chromium'
        run: |
          # Stop the existing application
          ~/deploy.sh stop
          
          # Copy the built application to the deployment directory
          sudo cp -R ./* ~/scrapi
          
          # Start the new version of the application
          ~/deploy.sh start

      - name: Verify deployment
        run: |
          sleep 10  # Give the application time to start
          if curl -s http://localhost:8080 > /dev/null; then
            echo "Application is running and responding"
          else
            echo "Application is not responding"
            cat /path/to/your/app/app.log
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: echo "Build or deployment failed."